const std = @import("std");

pub fn build(b: *std.Build) void {
    const target = b.standardTargetOptions(.{});
    const optimize = b.standardOptimizeOption(.{});
    const lexer_module = b.createModule(.{ .root_source_file = b.path("src/lexer.zig"), .target = target, .optimize = optimize });
    const ast_module = b.createModule(.{ .root_source_file = b.path("src/ast.zig"), .target = target, .optimize = optimize });
    const parser_module = b.createModule(.{ .root_source_file = b.path("src/parser.zig"), .target = target, .optimize = optimize });
    const checker_module = b.createModule(.{ .root_source_file = b.path("src/checker.zig"), .target = target, .optimize = optimize });
    const ast_printer_module = b.createModule(.{ .root_source_file = b.path("src/astprinter.zig"), .target = target, .optimize = optimize });
    const cli_module = b.createModule(.{ .root_source_file = b.path("src/cli.zig"), .target = target, .optimize = optimize });
    const fetcher_module = b.createModule(.{ .root_source_file = b.path("src/fetcher.zig"), .target = target, .optimize = optimize });
    ast_module.addImport("lexer", lexer_module);
    parser_module.addImport("lexer", lexer_module);
    parser_module.addImport("ast", ast_module);
    checker_module.addImport("lexer", lexer_module);
    checker_module.addImport("ast", ast_module);
    ast_printer_module.addImport("lexer", lexer_module);
    ast_printer_module.addImport("parser", parser_module);
    ast_printer_module.addImport("ast", ast_module);
    const exe = b.addExecutable(.{ .name = "ziguana", .root_module = b.createModule(.{ .root_source_file = b.path("src/main.zig"), .target = target, .optimize = optimize }) });
    exe.root_module.addImport("lexer", lexer_module);
    exe.root_module.addImport("ast", ast_module);
    exe.root_module.addImport("parser", parser_module);
    exe.root_module.addImport("checker", checker_module);
    exe.root_module.addImport("astprinter", ast_printer_module);
    exe.root_module.addImport("cli", cli_module);
    exe.root_module.addImport("fetcher", fetcher_module);
    b.installArtifact(exe);
    const run_cmd = b.addRunArtifact(exe);
    run_cmd.step.dependOn(b.getInstallStep());
    if (b.args) |args| run_cmd.addArgs(args);
    const run_step = b.step("run", "Run ziguana");
    run_step.dependOn(&run_cmd.step);
    const lexer_tests = b.addTest(.{ .root_module = b.createModule(.{ .root_source_file = b.path("tests/lexertest.zig"), .target = target, .optimize = optimize }) });
    lexer_tests.root_module.addImport("lexer", lexer_module);
    const parser_tests = b.addTest(.{ .root_module = b.createModule(.{ .root_source_file = b.path("tests/parsertest.zig"), .target = target, .optimize = optimize }) });
    parser_tests.root_module.addImport("lexer", lexer_module);
    parser_tests.root_module.addImport("ast", ast_module);
    parser_tests.root_module.addImport("parser", parser_module);
    const checker_tests = b.addTest(.{ .root_module = b.createModule(.{ .root_source_file = b.path("tests/checkertest.zig"), .target = target, .optimize = optimize }) });
    checker_tests.root_module.addImport("lexer", lexer_module);
    checker_tests.root_module.addImport("ast", ast_module);
    checker_tests.root_module.addImport("parser", parser_module);
    checker_tests.root_module.addImport("checker", checker_module);
    const run_lexer_tests = b.addRunArtifact(lexer_tests);
    const run_parser_tests = b.addRunArtifact(parser_tests);
    const run_checker_tests = b.addRunArtifact(checker_tests);
    const test_step = b.step("test", "Run unit tests");
    test_step.dependOn(&run_lexer_tests.step);
    test_step.dependOn(&run_parser_tests.step);
    test_step.dependOn(&run_checker_tests.step);
}
